import { Inter } from "next/font/google";
import "./globals.css";
import LanguageSelector from "./_components/flagComponents/flagSelector";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className={inter.className}>
        <><LanguageSelector/>{children}</>
      </body>
    </html>
  );
}
